#!/usr/bin/env python3
"""Generate the public factory reference from executable registries."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
REPO_ROOT = ROOT.parent if (ROOT.parent / ".github").exists() else ROOT
DEFAULT_OUT = ROOT / "legacy-docs" / "generated" / "factory-kernel-reference.md"

SOURCE_FILES = [
    "../docs/factory-workflow.catalog.json",
    "agents/worker-registry.public.json",
    "agents/worker-profiles.public.json",
    "agents/hermes-profile-bindings.public.json",
    "templates/factory-operating-system-registry.json",
    "templates/method-engine-registry.json",
    "../docs/public-surface.manifest.json",
]


def load_json(rel: str) -> dict[str, Any]:
    base = REPO_ROOT if rel.startswith("../") else ROOT
    clean = rel[3:] if rel.startswith("../") else rel
    return json.loads((base / clean).read_text(encoding="utf-8"))


def rel(path: Path) -> str:

    try:
        return path.relative_to(ROOT).as_posix()
    except ValueError:
        return path.relative_to(REPO_ROOT).as_posix()


def md(value: Any) -> str:
    text = str(value if value is not None else "").replace("\n", " ").strip()
    text = text.replace("|", "\\|")
    return text or "-"


def join_items(value: Any, *, limit: int | None = None) -> str:
    if not isinstance(value, list):
        return md(value)
    items = [str(item) for item in value if str(item).strip()]
    if limit is not None and len(items) > limit:
        shown = items[:limit]
        return md(", ".join(shown) + f", +{len(items) - limit} more")
    return md(", ".join(items))


def schema_files() -> list[str]:
    return sorted(path.relative_to(ROOT).as_posix() for path in (ROOT / "schemas").glob("*.json"))


def template_files() -> list[str]:
    return sorted(path.relative_to(ROOT).as_posix() for path in (ROOT / "templates").glob("*") if path.is_file())


def command_family() -> list[str]:
    factoryctl = (ROOT / "scripts" / "factoryctl.py").read_text(encoding="utf-8")
    commands: list[str] = []
    for line in factoryctl.splitlines():
        line = line.strip()
        if line.startswith('"') and line.endswith('",') and len(line) > 3:
            token = line.strip('",')
            if token.startswith(("validate-", "compile-", "capability-", "operating-", "method-", "route-", "signal-")):
                commands.append(token)
    return sorted(set(commands))


def generated_text() -> str:
    workflow = load_json("../docs/factory-workflow.catalog.json")
    worker_registry = load_json("agents/worker-registry.public.json")
    worker_profiles = load_json("agents/worker-profiles.public.json")
    bindings = load_json("agents/hermes-profile-bindings.public.json")
    operating_systems = load_json("templates/factory-operating-system-registry.json")
    method_engines = load_json("templates/method-engine-registry.json")
    public_surface = load_json("../docs/public-surface.manifest.json")

    phases = workflow.get("phases", [])
    workers = worker_registry.get("workers", [])
    profiles = worker_profiles.get("profiles", {})
    binding_profiles = bindings.get("profiles", bindings.get("bindings", []))
    os_entries = operating_systems.get("entries", [])
    engines = method_engines.get("engines", [])
    schemas = schema_files()
    templates = template_files()
    commands = command_family()

    lines: list[str] = [
        "# Factory Kernel Reference",
        "",
        "> Document status: GENERATED CURRENT REFERENCE.",
        "> Current authority: `scripts/generate_factory_reference_docs.py`, public registries, schemas, templates, tests and `factoryctl`.",
        "> Runtime boundary: This document explains the public factory kernel. Hermes Kanban remains the runtime source of truth for live cards, workers, runs, comments and transitions.",
        "",
        "This file is generated by `factory/scripts/generate_factory_reference_docs.py`. Do not edit it by hand.",
        "",
        "## Simple Picture",
        "",
        "Overkill Factory is like a product assembly line.",
        "",
        "A request enters the line. The factory checks the sources, decides the safe route, gives work to specialist agents, asks for proof, reviews the proof and only then lets the work move forward.",
        "",
        "Agents do the work; contracts choose the path. A worker can write code, study a product or review security, but the worker does not get to invent the phase, skip a gate or approve its own result.",
        "",
        "Done without evidence is only a claim. Receipt Five, review, runtime state and promotion packets are the proof path.",
        "",
        "## Generated From",
        "",
    ]
    lines.extend(f"- `{source}`" for source in SOURCE_FILES)
    lines.extend(
        [
            "",
            "## Counts",
            "",
            "| Area | Count | Source |",
            "| --- | ---: | --- |",
            f"| Factory phases | {len(phases)} | `docs/factory-workflow.catalog.json` |",
            f"| Public workers | {len(workers)} | `agents/worker-registry.public.json` |",
            f"| Worker profiles | {len(profiles)} | `agents/worker-profiles.public.json` |",
            f"| Hermes profile bindings | {len(binding_profiles)} | `agents/hermes-profile-bindings.public.json` |",
            f"| Operating systems | {len(os_entries)} | `templates/factory-operating-system-registry.json` |",
            f"| Method engines | {len(engines)} | `templates/method-engine-registry.json` |",
            f"| JSON schemas | {len(schemas)} | `schemas/*.json` |",
            f"| Templates | {len(templates)} | `templates/*` |",
            f"| Public surfaces | {len(public_surface.get('surfaces', []))} | `docs/public-surface.manifest.json` |",
            "",
            "## Factory Phases",
            "",
            "| Phase | Name | Required artifacts | Gates | Workers | What must not happen |",
            "| --- | --- | --- | --- | --- | --- |",
        ]
    )
    for phase in phases:
        lines.append(
            "| "
            + " | ".join(
                [
                    md(phase.get("phase_id")),
                    md(phase.get("phase_name")),
                    join_items(phase.get("required_artifacts"), limit=5),
                    join_items(phase.get("required_gates"), limit=4),
                    join_items(phase.get("required_workers"), limit=4),
                    join_items(phase.get("blocked_actions"), limit=3),
                ]
            )
            + " |"
        )

    lines.extend(
        [
            "",
            "## Worker Registry",
            "",
            "| Worker | Phases | Output | Maximum authority | Evidence required |",
            "| --- | --- | --- | --- | --- |",
        ]
    )
    for worker in workers:
        lines.append(
            "| "
            + " | ".join(
                [
                    md(worker.get("worker_id")),
                    join_items(worker.get("phase"), limit=7),
                    md(worker.get("output_contract")),
                    md(worker.get("authority_max")),
                    join_items(worker.get("evidence_required"), limit=5),
                ]
            )
            + " |"
        )

    lines.extend(
        [
            "",
            "## Worker Profiles",
            "",
            "| Profile | Worker | Topology | What it may do | What it must not do |",
            "| --- | --- | --- | --- | --- |",
        ]
    )
    for profile_name, profile in sorted(profiles.items()):
        authority = profile.get("authority", {})
        lines.append(
            "| "
            + " | ".join(
                [
                    md(profile_name),
                    md(profile.get("worker_id")),
                    md(profile.get("topology")),
                    join_items(authority.get("may"), limit=4),
                    join_items(authority.get("must_not"), limit=5),
                ]
            )
            + " |"
        )

    lines.extend(
        [
            "",
            "## Operating Systems",
            "",
            "| OS | Priority | Status | Owner | Purpose | Proof commands |",
            "| --- | --- | --- | --- | --- | --- |",
        ]
    )
    for entry in os_entries:
        lines.append(
            "| "
            + " | ".join(
                [
                    md(entry.get("display_name")),
                    md(entry.get("priority")),
                    md(entry.get("status")),
                    md(entry.get("owner_worker")),
                    md(entry.get("purpose")),
                    join_items(entry.get("enforcement_command_refs"), limit=5),
                ]
            )
            + " |"
        )

    lines.extend(
        [
            "",
            "## Method Engines",
            "",
            "| Engine | Family | Trigger routes | Required artifacts | Required gates | Forbidden shortcuts |",
            "| --- | --- | --- | --- | --- | --- |",
        ]
    )
    for engine in engines:
        lines.append(
            "| "
            + " | ".join(
                [
                    md(engine.get("display_name")),
                    md(engine.get("method_family")),
                    join_items(engine.get("trigger_routes"), limit=5),
                    join_items(engine.get("required_artifacts"), limit=5),
                    join_items(engine.get("required_gates"), limit=4),
                    join_items(engine.get("forbidden_shortcuts"), limit=4),
                ]
            )
            + " |"
        )

    lines.extend(
        [
            "",
            "## Machine Contracts",
            "",
            "These are the public JSON schemas the factory exposes. They are not decoration; validators and tests use them as machine contracts.",
            "",
        ]
    )
    lines.extend(f"- `{path}`" for path in schemas)

    lines.extend(
        [
            "",
            "## Templates",
            "",
            "Templates are starter records paired with schemas. They are examples of valid shape, not proof that a real product is done.",
            "",
        ]
    )
    lines.extend(f"- `{path}`" for path in templates)

    lines.extend(
        [
            "",
            "## CLI Surface",
            "",
            "The generated reference checks the command surface by scanning `scripts/factoryctl.py`. Use `docs/en/11-repository-reference.md` for operator examples.",
            "",
        ]
    )
    lines.extend(f"- `factoryctl {command}`" for command in commands[:80])
    if len(commands) > 80:
        lines.append(f"- `+{len(commands) - 80} more factoryctl commands in docs/en/11-repository-reference.md`")

    lines.extend(
        [
            "",
            "## Public Surface Rule",
            "",
            "Manual prose can explain the factory, but it cannot become stronger than the contracts. Public documentation must point back to source files, validators, schemas or tests. If a document cannot be traced to those sources, it is not a current factory reference.",
            "",
            "Regenerate and check this file with:",
            "",
            "```bash",
            "python scripts/generate_factory_reference_docs.py",
            "python scripts/generate_factory_reference_docs.py --check",
            "```",
        ]
    )
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate the public Overkill Factory kernel reference.")
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    parser.add_argument("--check", action="store_true", help="Fail if the generated reference is not up to date.")
    args = parser.parse_args()

    text = generated_text()
    out = args.out if args.out.is_absolute() else ROOT / args.out
    if args.check:
        if not out.exists():
            print(f"{rel(out)}: generated reference is missing", file=sys.stderr)
            return 1
        current = out.read_text(encoding="utf-8")
        if current != text:
            print(f"{rel(out)}: generated reference is stale; run python scripts/generate_factory_reference_docs.py", file=sys.stderr)
            return 1
        print("OK")
        return 0

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text, encoding="utf-8")
    print(rel(out))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
