from __future__ import annotations

import importlib.util
import json
import subprocess
import sys
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def load_generator():
    path = ROOT / "scripts" / "generate_factory_reference_docs.py"
    spec = importlib.util.spec_from_file_location("generate_factory_reference_docs", path)
    assert spec is not None
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(module)
    return module


class GeneratedFactoryReferenceDocsTest(unittest.TestCase):
    def test_generated_reference_is_current(self) -> None:
        result = subprocess.run(
            [sys.executable, "scripts/generate_factory_reference_docs.py", "--check"],
            cwd=ROOT,
            text=True,
            capture_output=True,
        )

        self.assertEqual(result.returncode, 0, result.stderr + result.stdout)

    def test_generated_reference_counts_match_public_contracts(self) -> None:
        generator = load_generator()
        text = generator.generated_text()

        workflow = json.loads((ROOT / "legacy-docs" / "factory-workflow.catalog.json").read_text(encoding="utf-8"))
        workers = json.loads((ROOT / "agents" / "worker-registry.public.json").read_text(encoding="utf-8"))
        profiles = json.loads((ROOT / "agents" / "worker-profiles.public.json").read_text(encoding="utf-8"))
        operating_systems = json.loads((ROOT / "templates" / "factory-operating-system-registry.json").read_text(encoding="utf-8"))
        method_engines = json.loads((ROOT / "templates" / "method-engine-registry.json").read_text(encoding="utf-8"))

        expected_rows = [
            f"| Factory phases | {len(workflow['phases'])} | `legacy-docs/factory-workflow.catalog.json` |",
            f"| Public workers | {len(workers['workers'])} | `agents/worker-registry.public.json` |",
            f"| Worker profiles | {len(profiles['profiles'])} | `agents/worker-profiles.public.json` |",
            f"| Operating systems | {len(operating_systems['entries'])} | `templates/factory-operating-system-registry.json` |",
            f"| Method engines | {len(method_engines['engines'])} | `templates/method-engine-registry.json` |",
        ]

        for row in expected_rows:
            with self.subTest(row=row):
                self.assertIn(row, text)

        for phrase in [
            "This file is generated by `scripts/generate_factory_reference_docs.py`",
            "Hermes Kanban remains the runtime source of truth",
            "Agents do the work; contracts choose the path",
            "Done without evidence is only a claim",
        ]:
            with self.subTest(phrase=phrase):
                self.assertIn(phrase, text)


if __name__ == "__main__":
    unittest.main()
